version: "3.6"
services:
  # NGINX:STABLE-ALPINE
  my_aplication_nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
    working_dir: /var/www/html
    volumes:
      - ./aplication:/var/www/html
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - my_aplication_php
  
  # PHP:8.1-FPM DOCKERFILE
  my_aplication_php:
    build: 
      args:
        user: user_application
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: php
    # image: sistema_comissao
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    working_dir: /var/www/html
    volumes:
       - ./aplication:/var/www/html
      #  - ./conf/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    # environment:
    #   XDEBUG_MODE: debug
    #   XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
  
  # NODE:20-ALPINE
  my_aplication_node:
    container_name: aplication_node
    image: node:20-alpine
    restart: always
    ports:
      - "5173:5173"
    tty: true
    volumes:
      - ./aplication:/var/www/html
    working_dir: /var/www/html
    command: >
      sh -c "npm install &&
             npm run dev"
    depends_on:
      - my_aplication_nginx
    
  # MYSQL:8.0
  my_aplication_mysql:
    container_name: mysql
    image: mysql:5.7.22
    ports:
      - '3306:3306'
    working_dir: /var/www/html
    volumes:
       - ./conf/mysql/data:/var/lib/mysql
    environment:
        MYSQL_DATABASE: basicus
        MYSQL_USER: user_aplicacao
        MYSQL_PASSWORD: shalom000
        MYSQL_ROOT_PASSWORD: shalom123