[supervisord]
logfile=/var/log/supervisord.log ; log principal do supervisor
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/var/run/supervisord.pid
nodaemon=true                    ; mantém o supervisor rodando em primeiro plano no container
user=root

[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work rabbitmq --queue=precos,default --tries=3 --backoff=3 --delay=3
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=user_application            ; roda o comando do laravel com o usuário seguro
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker.log
stopwaitsecs=3600